### ISSUE TITLE
Use codecov.io links to latest working revision

### ISSUE THREAD

**Issue by mgaudet** [marco-c/code-coverage-reports#15]
I'm seeing 

<img width="785" alt="image" src="https://user-images.githubusercontent.com/2906003/38992881-5f2030b8-43e2-11e8-8f75-7b1dcc20b6c5.png">

Trying to view https://codecov.io/gh/marco-c/gecko-dev/src/master/js/src/jit/TypePolicy.cpp

**Comment by marco-c** [comment]
There's a temporary problem with codecov.io, it should be fixed soon.

**Comment by marco-c** [comment]
In the meantime, you can see the file at the previous revision: https://codecov.io/gh/marco-c/gecko-dev/src/59a9a86553e9bfd9277202748ff791fd9bc0713b/js/src/jit/TypePolicy.cpp.

**Comment by mgaudet** [comment]
Oh, thanks :D
