### ISSUE TITLE
Please show the first & last modification date on a file

### ISSUE THREAD

**Issue by sylvestre** [marco-c/code-coverage-reports#2]
For example, here: https://marco-c.github.io/code-coverage-reports/#dom/xslt/xslt
it would be helpful to know if the file is brand new or super old.
This would help doing a quick spot check to know if it is actually dead or not.

**Comment by marco-c** [comment]
Depends on https://github.com/mozilla-releng/services/issues/803.

**Comment by Juniar-II** [comment]
There are many .cpp, .h and Json files on repo. Which files relates with this bug.

**Comment by marco-c** [comment]
Could you elaborate your question more? I'm not sure what you're talking about.

**Comment by Juniar-II** [comment]
If I was to write a code where would I put it. Should I create a new .js file.

**Comment by marco-c** [comment]
> If I was to write a code where would I put it. Should I create a new .js file.

No, the code would go here: https://github.com/marco-c/code-coverage-reports/blob/gh-pages/app.js.

But as I said a few comments ago, this depends on https://github.com/mozilla-releng/services/issues/803.
"Depends on" means that the other issue must be fixed first.

**Comment by Juniar-II** [comment]
Are there any back end issues on "mozilla-releng/services#803." It is not listed?

**Comment by marco-c** [comment]
@Juniar-II what do you mean? Can you elaborate your question?

**Comment by Juniar-II** [comment]
There are a number of bugs related with "mozilla-releng/services#803." and it seems the back end needs to be fixed first.

**Comment by marco-c** [comment]
> There are a number of bugs related with "mozilla-releng/services#803." and it seems the back end needs to be fixed first.

No, https://github.com/mozilla-releng/services/issues/803 is just a feature that we need to implement first. The discussion you see there is about setting up the repository for development, but it is actually unrelated to the feature itself.
