### ISSUE TITLE
Add size of the files in the zero coverage report

### ISSUE THREAD

**Issue by marco-c** [marco-c/code-coverage-reports#4]
It would be interesting to sort by file size instead of number of uncovered files.

**Comment by akshitac8** [comment]
Hey,
Is this issue up for solving?

**Comment by marco-c** [comment]
Hello @akshitac8, yes it is available, but this actually depends on https://github.com/mozilla-releng/services/issues/803. Without support in the backend, we can't do it.

**Comment by akshitac8** [comment]
Ohkay
@marco-c so how should I proceed with it?

**Comment by marco-c** [comment]
If you would be interested in backend work, you could try fixing https://github.com/mozilla-releng/services/issues/803. If you want to do it, please send me an email and I'll explain you how to setup that repository.
Otherwise, you can try with one of the other good-first-bugs in this repo.
