### ISSUE TITLE
The filters at the top of the report page don't work

### ISSUE THREAD

**Issue by marco-c** [marco-c/code-coverage-reports#42]
We should decide which ones we want to keep, and remove the ones we don't want to keep.

N.B.: They work in the zero coverage report, but not in the full report.

**Comment by La0** [comment]
That seems impossible to do cleanly without modifying the backend.
The path request would add an argument `?extensions=js+cpp+c` to limit folders containing such files.

**Comment by marco-c** [comment]
Indeed, so maybe we can remove them for now and add them if/when somebody asks us for the feature.

**Comment by marco-c** [comment]
Fixed by #53.
