### ISSUE TITLE
Start loading path coverage earlier

### ISSUE THREAD

**Issue by marco-c** [marco-c/code-coverage-reports#57]
We probably don't need to wait for onLoad in order to start loading the data.

**Comment by La0** [comment]
Using `DOMContentLoaded` can start the retrieval earlier, but makes for a way more complex workflow. Not sure it's worth it.

**Comment by marco-c** [comment]
On my machine:
DOMContentLoaded - 960 ms
onLoad - 1,3 s

If we move to DOMContentLoaded, we'd save almost half a second.
If we moved to even earlier (probably we can do that, as we shouldn't need the DOM to load the data), we'd save almost a second and a half.

**Comment by La0** [comment]
Alright, i'll try a bit more
