### ISSUE TITLE
Graph + file displayed on the same page

### ISSUE THREAD

**Issue by calixteman** [marco-c/code-coverage-reports#59]
![image](https://user-images.githubusercontent.com/5641725/60678721-b8379480-9e85-11e9-868b-cc8187c45e0f.png)

STR:
 1. Go to accessible/base/ARIAStateMap.cpp
 2. Prev arrow and then Next arrow when stuff is loading

**Comment by La0** [comment]
How did you manage to get that ?

Le jeu. 4 juil. 2019 à 18:01, calixteman <notifications@github.com> a
écrit :

**Comment by marco-c** [comment]
Calixte put STR in the first comment.
