### ISSUE TITLE
Please add a link "add new issues"

### ISSUE THREAD

**Issue by sylvestre** [marco-c/code-coverage-reports#7]

**Comment by rhcu** [comment]
Hi! 
I am interested to work on this issue. Can I start if it is still available?

**Comment by sylvestre** [comment]
Sure, please go ahead!

**Comment by rhcu** [comment]
It could be a strange question, but I cannot find any HTML files in this repository. Can you help me with this?

**Comment by marco-c** [comment]
@rhcu the code itself is in the gh-pages branch of the repository.
